const beverages = [
  {
    name: 'Hazy APA',
    alcohol: '0% obj.',
    filtered: false,
    tale:
      'Spróbuj jak smakuje luz z American Pale Ale. Tradycyjnie warzone, nieklarowane, więc mgliste. Jasne, orzeźwiające, o wyczuwalnej goryczce. Wzbogacone cytrusowymi nutami pochodzącymi z wyselekcjonowanych odmian amerykańskich chmieli. Cornelius APA - mglisty z natury, wyrazisty w smaku - najsmaczniejszy, gdy przed otwarciem obrócisz puszkę na chwilę denkiem do góry.',
    barcode: '5905689310363',
    ingredients: {
      pl:
        'woda, słody: jęczmienny, pszeniczny, chmiele: Magnum, Cascade, Amarillo, Mosaic, drożdże',
      en:
        'water, malts: barley, wheat, hops: Magnum, Cascade, Amarillo, Mosaic, yests',
    },
    producer: 'Sulimar Sp. z o.o.',
    place: 'Piotrków Trybunalski',
    series: 'Cornelius',
    fermentation: 'top',
    pasteurisation: true,
    alcohol: 'do 0,5%',
    container: '500ml puszka srebrna 17cm',
    bitterness: 40,
    price: '4,40 zł',
    added: '27 czerwca 2020, 18:21',
  },
  {
    name: 'Hazy IPA',
    alcohol: '0% obj.',
    filtered: false,
    tale:
      'Spróbuj jak smakuje luz z India Pale Ale. Tradycyjnie warzone, nieklarowane, więc mgliste. Jasne, silniej chmielone, o intensywnej goryczce. Wzbogacone owocowymi nutami pochodzącymi z wyselekcjonowanych odmian chmieli. Cornelius IPA - mglisty z natury, wyrazisty w smaku - najsmaczniejszy, gdy przed otwarciem obrócisz puszkę na chwilę denkiem do góry.',
    barcode: '5905689310370',
    ingredients: {
      pl:
        'woda, słody: jęczmienny, pszeniczny, chmiele: Magnum, Cascade, Amarillo, Mosaic, drożdże',
      en:
        'water, malts: barley, wheat, hops: Magnum, Cascade, Amarillo, Mosaic, yests',
    },
    producer: 'Sulimar Sp. z o.o.',
    place: 'Piotrków Trybunalski',
    series: 'Cornelius',
    fermentation: 'top',
    pasteurisation: true,
    alcohol: 'do 0,5%',
    container: '500ml puszka srebrna 17cm',
    bitterness: 55,
    price: '4,45 zł',
    added: '27 czerwca 2020, 18:27',
  },
  {
    name: 'Free Way',
    brand: 'AleBrowar',
    style: 'Non-Alcoholic IPA',
    barcode: '5907222039526',
    container: '500ml butelka brązowa 26cm',
    alcohol: 'mniej niż 0.5%',
    extract: '7% wag.',
    filtration: false,
    pasteurisation: true,
    place: 'Lębork',
    tale: {
      pl:
        'Kolarze i kolarzówki, nareszcie droga jest wolna - można wypłenić bidony aromatycznym i smakowitym, bezalkoholowym IPA i cisnąć przed siebie. Na mecie czeka Was nagroda, pełnia satysfakcji i czyste sumienie podczas kontroli antyprocentowej.',
      en:
        'Dear cyclists! Finally the road is free - you can fill the water bottles with aromatic and tasty, non-alcoholic IPA and run ahead. At the finish line there is a prize waiting, full satisfaction and a clear conscience during roadside checks',
    },
    ingredients: {
      pl:
        'woda, słody: Pale Ale, pszeniczny, żytni, Vicing Cara, płatki owsiane, herbata Sencha Earl Grey, chmiele: Cascade, Amarillo, Citra, Mosaic, drożdże',
      en:
        'water, malts: Pale Ale, wheat, rye, Viking Cara, flaked oats, tea sencha Earl Grey, hops: Cascade, Amarillo, Citra, Mosaic, yeast',
    },
    bitterness: '5/8',
    sweetness: '3/8',
    powerness: '1/8',
    price: '7,50 zł',
    added: '27 czerwca 2020, 18:38',
  },
  {
    name: 'Rowerzysta',
    brand: 'Browar Profesja',
    style: 'Sour Ale z rabarbarem',
    alcohol: '0.5%',
    extract: '7 Plato',
    temterature: '8-12',
    ingredients:
      'woda, słody: jęczmienny, pszeniczny, sok jabłkowy z soku zagęszczonego, sok z cytryny z soku zagęszczonego, sok rabarbarowy z soku zagęszczonego, aromat naturalny rabarbaru, barwnik naturalny, przeciwutleniacz (kwas askorbinowy), kwas (kwas cytrynowy), chmiel, drożdże WLS17 Sacharomyces Ludwigi, bakterie',
    filtered: false,
    pasteurisation: true,
    bitterness: '0.5/5',
    place: 'Wrocław',
    barcode: '5904730658843',
    container: 'butelka 500ml brązowa 25cm',
    price: '5.90 zł',
    added: '27 czerwca 2020, 18:44',
  },
  {
    name: 'Pomelo Nealko',
    brand: 'Litovel',
    container: 'butelka 500ml brązowa 26cm',
    alcohol: 'do 0.5%',
    barcode: '8593875517312',
    tale: 'zdjęcie',
    price: '3,15 zł',
    added: '27 czerwca 2020, 18:51',
  },
  {
    name: 'The Game #2',
    brand: 'Raduga',
    series: 'Egzotyczne klimaty',
    alcohol: 'poniżej 0.5%',
    style: 'Bezalkoholowe IPA Marakuja & Morela',
    bitterness: '2/10',
    barcode: '5902176770747',
    filtered: false,
    pasteurisation: true,
    container: '500ml puszka czarna',
    notes: 'A jest napisane butelka bezzwrotna',
    ingredients:
      'woda, słody: jęczmienny, pszeniczny, sok z marakui i moreli, chmiele, drożdże',
    contract: 'wyprodukowane w Polsce dla Raduga',
    price: '6.90 zł',
    added: '27 czerwca 2020, 18:57',
  },
  {
    name: 'Zenzero',
    brand: 'Browar Nepomucen',
    style: 'Lite Ginger Ale',
    alcohol: '0.5% obj.',
    tale:
      'Imbir im Bier, można rzec w jakimś nordyckim narzeczu, ale brzmi to ciężko. A nasze piwo to lekkie, niskoalkoholowe Ale. Dlatego sięgnęliśmy do włoskiego słownika i nazwaliśmy je Zenzero, i zawarliśmy w tym słowie wszystko co najlepsze w naszym piwie. Imbir, równowaga i prawie zero alkoholu.',
    barcode: '5907709756496',
    place: 'Jutrosin',
    bitterness: '0/6',
    ingredients:
      'woda, imbir, słody: jęczmienny, pszeniczny, cukier, laktoza, słód żytni, chmiel, drożdże górnej fermentacji z własnej propagacji',
    temperature: '8-10',
    filtration: false,
    pasteurisation: true,
    container: 'butelka brązowa 500ml 25cm',
    price: '6.60 zł',
    added: '27 czerwca 2020, 20:15',
  },
  {
    brand: 'Inne Beczki',
    name: '338 803',
    tale:
      "Nie ma Rak'n'rolla bez procentów. \n\n Do szczęścia potrzebujemy procentów, ale innych, niż myślisz. Przekaż 1% podatku na przejście przez raka. Przelej na zdrowie KRS 0000 338 803 \n\n Kupując, wspierasz Fundację Rak'n'Roll",
    place: 'Błonie',
    ingredients: 'woda, słód jęczmienny, chmiel, drożdże, sól',
    notes: '"Głowny piwowar Maciej Piaszczyński"',
    barcode: '5905669683685',
    contract: 'Browar Błonie',
    pasteurisation: true,
    filtration: false,
    alcohol: 'mniej niż 0.5%',
    price: '6.50 zł',
    added: '27 czerwca 2020, 20:21',
  },
  {
    name: 'Pilot',
    notes: 'Już jest w bazie, popraw tylko zdjęcie i dodaj cenę 6.50 zł ',
  },
  {
    brand: 'Piwo z Żuka',
    ingredients:
      'woda, słody: żytni, pilzneński, monachijski, chmiele: Zeus, Citra, Mosaic, Cascade, Centential, drożdże',
    alcohol: 'poniżej 0.5%',
    extract: '6.5%',
    pasteurisation: true,
    filtration: false,
    contract: 'Browar Wąsosz',
    place: 'Wąsosz, Konopiska',
    container: 'butelka 500ml brązowa 25cm',
    name: '0% Rye AIPA',
    barcode: '5902448151274',
    price: '6.00 zł',
    added: '27 czerwca 2020, 20:27',
  },
];
